### ISSUE TITLE
Logic error?

### ISSUE THREAD

**Issue by alexpratte16** [borisRadonic/ToolboxR#8]
https://github.com/borisRadonic/ToolboxR/blob/2286009fea63540a150abaf61c1583e5b710b639/CntrLibrary/Source/PMSMotor.cpp#L127

If I am understanding this correctly line 125 checks if abs(_aM) < epsilon.
This would only be true if _aM== 0

The comment on line 127 says //acceleration is != 0 which seems to be incorrect?

Then on line 128: if (abs( (_iq * _Ktq) - ( (1.00/ _invJ) * _aM)) < _Tsf)
if _aM == 0 then
(abs( (_iq * _Ktq) - ( (1.00/ _invJ) * _aM)) < _Tsf) becomes
(abs( (_iq * _Ktq) < _Tsf) 

Which is the same check on line 139 meaning that no matter which branch you take from the if statement on line 125 you will get the same result?

Please correct me if I am wrong I really appreciated your article on embedded.com

**Comment by borisRadonic** [comment]
Hi Alex,
 std::numeric_limits<std::double_t>::min() is approximately "2.2250738585072014e-308". Every value with an absolute value less than this can be considered as 0.000000. This is a standard procedure to check if a value is nearly zero.
Regarding the comment on line 127, it was indeed incorrect. I have corrected the comment to better reflect the logic in the code.
// acceleration is nearly zeroYou are correct that the check on line 128 and the subsequent condition on line 139 appear similar. The difference lies in the branching logic and the resulting assignment to _static_friction. Depending on the conditions, _static_friction is assigned differently.Additionally, there are unit tests available that you can run to verify this logic. The unit tests cover various scenarios to ensure the correctness of the implementation.

There is a new version on github. 

I appreciate your attention to detail and your feedback. It helps improve the clarity and accuracy of the code and related documentation.

Best RegardsBoris


    Am Samstag, 25. Mai 2024 um 23:32:53 MESZ hat Alex Pratte ***@***.***> Folgendes geschrieben:  
 
 


https://github.com/borisRadonic/ToolboxR/blob/2286009fea63540a150abaf61c1583e5b710b639/CntrLibrary/Source/PMSMotor.cpp#L127

If I am understanding this correctly line 125 checks if abs(_aM) < epsilon.
This would only be true if _aM== 0

The comment on line 127 says //acceleration is != 0 which seems to be incorrect?

Then on line 128: if (abs( (_iq * _Ktq) - ( (1.00/ _invJ) * _aM)) < _Tsf)
if _aM == 0 then
(abs( (_iq * _Ktq) - ( (1.00/ _invJ) * _aM)) < _Tsf) becomes
(abs( (_iq * _Ktq) < _Tsf)

Which is the same check on line 139 meaning that no matter which branch you take from the if statement on line 125 you will get the same result?

Please correct me if I am wrong I really appreciated your article on embedded.com
